name: ktp-qwerty

volumes:
  data:
  logs:

services:
  core:
    container_name: core
    build:
      dockerfile_inline: |
        FROM jlgingrich/disnake
        COPY ./exts ./exts
        COPY ./data ./data
    env_file:
      - .env
    volumes:
      - data:/app/data
      - logs:/app/logs
