name: ktp-qwerty

volumes:
  logs:

services:
  core:
    container_name: core
    build:
      dockerfile_inline: |
        FROM jlgingrich/disnake
        COPY ./plugins /app/core/plugins/
    env_file:
      - .env
    volumes:
      - logs:/app/logs
